name: ci-cd
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
concurrency:
  group: deploy-main
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install -r app/requirements.txt
      - run: python -c "import importlib; importlib.import_module('app.main')"
  build_and_push:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_REPO }}:${{ github.sha }}
            ${{ secrets.IMAGE_REPO }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
      - run: |
          helm dependency update helm/platform
          helm upgrade --install "${{ secrets.HELM_RELEASE }}" helm/platform             --kubeconfig kubeconfig             --namespace "${{ secrets.KUBE_NAMESPACE }}"             --create-namespace             --set image.repository="${{ secrets.IMAGE_REPO }}"             --set image.tag="${{ github.sha }}"
